export type ModelHubItem = {
  id: string;
  github_id: number;
  full_name: string;
  owner: string;
  name: string;
  html_url: string;
  description: string | null;
  language: string | null;
  license_spdx: string | null;
  topics: string[];
  stargazers_count: number;
  forks_count: number;
  open_issues_count: number;
  watchers_count: number;
  pushed_at: string | null;
  github_created_at: string | null;
  github_updated_at: string | null;
  homepage: string | null;
  default_branch: string | null;
  category: string;
  task_types: string[];
  domain_tags: string[];
  model_signals: string[];
  quality_flags: string[];
  recommendation_score: number;
  recommendation_reason: string | null;
  curator_summary: string | null;
  curated_recommendation_reason: string | null;
  project_understanding: string | null;
  risk_notes: string | null;
  target_users: string[];
  curation_tags: string[];
  curated_score: number | null;
  curation_status: string | null;
  curated_at: string | null;
  curated_by: string | null;
  curation_notes: string | null;
  source_queries: string[];
  last_synced_at: string | null;
};

export type ModelHubResponse = {
  items: ModelHubItem[];
  total: number;
  category: string | null;
  lastSyncedAt: string | null;
  configured: boolean;
};
