-- Remote Supabase public schema contract export.
-- Generated by src/scripts/export-db-contracts.mjs.
-- Read-only source operation: metadata queries inside BEGIN READ ONLY.
-- Do not run this file directly against production without DBA review.
-- Exported at: 2026-04-26T02:16:43.453Z

create schema if not exists public;

-- Extensions
create extension if not exists "pg_cron" with schema "pg_catalog";
create extension if not exists "pg_graphql" with schema "graphql";
create extension if not exists "pg_net" with schema "public";
create extension if not exists "pg_stat_statements" with schema "extensions";
create extension if not exists "pgcrypto" with schema "extensions";
create extension if not exists "supabase_vault" with schema "vault";
create extension if not exists "uuid-ossp" with schema "extensions";
create extension if not exists "wrappers" with schema "extensions";

-- Tables
create table "public"."ai_analysis_queue" (
  "id" uuid default gen_random_uuid() not null,
  "paper_id" uuid not null,
  "user_id" uuid,
  "provider" text default 'platform'::text not null,
  "status" text default 'pending'::text not null,
  "priority" integer default 0 not null,
  "error_message" text,
  "attempts" integer default 0 not null,
  "max_attempts" integer default 3 not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "completed_at" timestamp with time zone
);

create table "public"."ai_digest_log" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "paper_id" uuid not null,
  "email_sent_to" text not null,
  "provider" text default 'platform'::text not null,
  "model_used" text,
  "status" text default 'sent'::text not null,
  "created_at" timestamp with time zone default now() not null
);

create table "public"."byok_usage_log" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "paper_id" uuid,
  "provider" text not null,
  "model" text not null,
  "usage_type" text default 'translate'::text not null,
  "input_tokens" integer,
  "output_tokens" integer,
  "status" text default 'success'::text not null,
  "error_message" text,
  "created_at" timestamp with time zone default now() not null
);

create table "public"."feed_recommendations" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "paper_id" uuid not null,
  "source_type" text default 'precision'::text not null,
  "recommendation_score" numeric(7,4) default 0 not null,
  "reason" text,
  "is_consumed" boolean default false not null,
  "consumed_at" timestamp with time zone,
  "batch_date" date default CURRENT_DATE not null,
  "created_at" timestamp with time zone default now() not null
);

create table "public"."journal_if_cache" (
  "id" uuid default gen_random_uuid() not null,
  "journal_name" text not null,
  "journal_abbr" text,
  "impact_factor" numeric(7,2),
  "jcr_quartile" text,
  "cas_zone" text,
  "issn" text,
  "eissn" text,
  "search_variants" text[] default '{}'::text[],
  "updated_at" timestamp with time zone default now()
);

create table "public"."journal_quality" (
  "id" uuid default gen_random_uuid() not null,
  "journal_name" text not null,
  "aliases" text[] default '{}'::text[] not null,
  "tier" text default 'core'::text not null,
  "weight" numeric(5,4) default 0.7 not null,
  "is_active" boolean default true not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "impact_factor" numeric(6,2),
  "jcr_quartile" text,
  "cas_zone" text,
  "is_featured" boolean default false not null,
  "es_last_sync_at" timestamp with time zone,
  "es_sync_status" text,
  "es_error" text,
  "es_raw" jsonb
);

create table "public"."journal_sync_log" (
  "id" uuid default gen_random_uuid() not null,
  "journal_quality_id" uuid not null,
  "journal_name" text not null,
  "sync_from" date not null,
  "sync_to" date not null,
  "papers_found" integer default 0 not null,
  "papers_passed" integer default 0 not null,
  "papers_new" integer default 0 not null,
  "status" text default 'success'::text not null,
  "error_message" text,
  "started_at" timestamp with time zone default now() not null,
  "finished_at" timestamp with time zone
);

create table "public"."keyword_synonyms" (
  "id" uuid default gen_random_uuid() not null,
  "canonical_keyword" text not null,
  "synonyms" text[] default '{}'::text[] not null,
  "title_required" text[] default '{}'::text[] not null,
  "category" text,
  "updated_at" timestamp with time zone default now(),
  "source" text default 'manual'::text,
  "llm_generated_at" timestamp with time zone,
  "pubmed_query_template" text
);

create table "public"."paper_research_topics" (
  "paper_id" uuid not null,
  "topic_id" uuid not null,
  "confidence" numeric(5,4) default 0 not null,
  "source" text default 'rule'::text not null,
  "matched_terms" text[] default '{}'::text[] not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "public"."paper_topics" (
  "paper_id" uuid not null,
  "topic" text not null,
  "score" numeric(5,4),
  "created_at" timestamp with time zone default now() not null
);

create table "public"."papers" (
  "id" uuid default gen_random_uuid() not null,
  "pmid" text not null,
  "doi" text,
  "title" text not null,
  "abstract" text,
  "journal" text,
  "publication_date" date,
  "pubmed_url" text not null,
  "authors" jsonb default '[]'::jsonb not null,
  "mesh_terms" text[] default '{}'::text[] not null,
  "keywords" text[] default '{}'::text[] not null,
  "is_open_access" boolean default false not null,
  "oa_pdf_url" text,
  "ai_analysis" jsonb,
  "source_payload" jsonb,
  "fetched_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "is_ai_med" boolean default false not null,
  "ai_med_score" numeric(5,4) default 0 not null,
  "quality_score" numeric(5,4) default 0 not null,
  "quality_tier" text default 'emerging'::text not null,
  "abstract_zh" text,
  "title_zh" text,
  "journal_if" numeric(7,2),
  "journal_jcr" text,
  "journal_cas_zone" text,
  "recommendation_reason" text,
  "recommendation_reason_en" text,
  "llm_processed_at" timestamp with time zone
);

create table "public"."profiles" (
  "id" uuid not null,
  "display_name" text,
  "role" text default 'doctor'::text not null,
  "specialty" text,
  "institution" text,
  "contact_email" text,
  "subscription_keywords" text[] default '{}'::text[] not null,
  "subscription_mesh_terms" text[] default '{}'::text[] not null,
  "is_active" boolean default true not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "byok_provider" text,
  "byok_api_key_encrypted" text,
  "byok_model" text,
  "ai_digest_enabled" boolean default true not null,
  "top_journals_only" boolean default false not null,
  "subscription_min_score" numeric(5,4) default 0 not null,
  "custom_journals" text[] default '{}'::text[] not null,
  "weekly_digest_enabled" boolean default true,
  "weekly_digest_day" integer default 0,
  "weekly_digest_last_sent" date
);

create table "public"."push_issue_items" (
  "issue_id" uuid not null,
  "paper_id" uuid not null,
  "rank" integer not null,
  "quality_score" numeric(5,4) default 0 not null,
  "created_at" timestamp with time zone default now() not null
);

create table "public"."push_issues" (
  "id" uuid default gen_random_uuid() not null,
  "issue_week_start" date not null,
  "status" text default 'draft'::text not null,
  "generated_at" timestamp with time zone default now() not null,
  "sent_at" timestamp with time zone,
  "meta" jsonb default '{}'::jsonb not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "public"."research_topics" (
  "id" uuid default gen_random_uuid() not null,
  "slug" text not null,
  "name_zh" text not null,
  "name_en" text not null,
  "description" text,
  "sort_order" integer default 0 not null,
  "is_active" boolean default true not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "public"."subject_categories" (
  "id" uuid default gen_random_uuid() not null,
  "name_zh" text not null,
  "name_en" text not null,
  "search_terms" text[] default '{}'::text[] not null,
  "recommended_journal_ids" uuid[] default '{}'::uuid[] not null,
  "source" text default 'manual'::text not null,
  "sort_order" integer default 0 not null,
  "is_active" boolean default true not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "public"."sync_state" (
  "key" text not null,
  "value" text not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "public"."user_journal_subscriptions" (
  "user_id" uuid not null,
  "journal_quality_id" uuid not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "public"."user_paper_interactions" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "paper_id" uuid not null,
  "is_read" boolean default false not null,
  "is_favorited" boolean default false not null,
  "read_at" timestamp with time zone,
  "favorited_at" timestamp with time zone,
  "pdf_emailed_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "public"."user_topic_subscriptions" (
  "user_id" uuid not null,
  "topic_id" uuid not null,
  "weight" numeric(5,4) default 1 not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "public"."user_weekly_push_deliveries" (
  "id" uuid default gen_random_uuid() not null,
  "issue_id" uuid not null,
  "user_id" uuid not null,
  "paper_id" uuid not null,
  "issue_week_start" date not null,
  "delivered_at" timestamp with time zone default now() not null
);

create table "public"."user_weekly_spotlight_deliveries" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "issue_week_start" date not null,
  "email_to" text not null,
  "spotlight_count" integer default 0 not null,
  "paper_ids" uuid[] default '{}'::uuid[] not null,
  "status" text default 'processing'::text not null,
  "trigger_source" text default 'cron'::text not null,
  "last_error" text,
  "sent_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "public"."weekly_reports" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "period_from" date not null,
  "period_to" date not null,
  "specialty_paper_ids" uuid[] default '{}'::uuid[] not null,
  "hotspot_paper_id" uuid,
  "crossover_paper_id" uuid,
  "email_status" text default 'pending'::text not null,
  "email_sent_at" timestamp with time zone,
  "email_error" text,
  "html_content" text,
  "created_at" timestamp with time zone default now() not null
);

-- Constraints
alter table only "public"."ai_analysis_queue" add constraint "ai_analysis_queue_provider_check" CHECK (provider = ANY (ARRAY['platform'::text, 'byok'::text]));
alter table only "public"."ai_analysis_queue" add constraint "ai_analysis_queue_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text]));
alter table only "public"."ai_analysis_queue" add constraint "ai_analysis_queue_paper_id_fkey" FOREIGN KEY (paper_id) REFERENCES papers(id) ON DELETE CASCADE;
alter table only "public"."ai_analysis_queue" add constraint "ai_analysis_queue_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table only "public"."ai_analysis_queue" add constraint "ai_analysis_queue_pkey" PRIMARY KEY (id);
alter table only "public"."ai_digest_log" add constraint "ai_digest_log_status_check" CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text, 'bounced'::text]));
alter table only "public"."ai_digest_log" add constraint "ai_digest_log_paper_id_fkey" FOREIGN KEY (paper_id) REFERENCES papers(id) ON DELETE CASCADE;
alter table only "public"."ai_digest_log" add constraint "ai_digest_log_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only "public"."ai_digest_log" add constraint "ai_digest_log_pkey" PRIMARY KEY (id);
alter table only "public"."byok_usage_log" add constraint "byok_usage_log_status_check" CHECK (status = ANY (ARRAY['success'::text, 'failed'::text]));
alter table only "public"."byok_usage_log" add constraint "byok_usage_log_usage_type_check" CHECK (usage_type = ANY (ARRAY['translate'::text, 'summarize'::text, 'pdf_analysis'::text, 'chat'::text]));
alter table only "public"."byok_usage_log" add constraint "byok_usage_log_paper_id_fkey" FOREIGN KEY (paper_id) REFERENCES papers(id) ON DELETE SET NULL;
alter table only "public"."byok_usage_log" add constraint "byok_usage_log_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only "public"."byok_usage_log" add constraint "byok_usage_log_pkey" PRIMARY KEY (id);
alter table only "public"."feed_recommendations" add constraint "feed_recommendations_source_type_check" CHECK (source_type = ANY (ARRAY['precision'::text, 'trending'::text, 'serendipity'::text]));
alter table only "public"."feed_recommendations" add constraint "feed_recommendations_paper_id_fkey" FOREIGN KEY (paper_id) REFERENCES papers(id) ON DELETE CASCADE;
alter table only "public"."feed_recommendations" add constraint "feed_recommendations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only "public"."feed_recommendations" add constraint "feed_recommendations_pkey" PRIMARY KEY (id);
alter table only "public"."feed_recommendations" add constraint "feed_recommendations_user_id_paper_id_batch_date_key" UNIQUE (user_id, paper_id, batch_date);
alter table only "public"."journal_if_cache" add constraint "journal_if_cache_pkey" PRIMARY KEY (id);
alter table only "public"."journal_if_cache" add constraint "journal_if_cache_journal_name_key" UNIQUE (journal_name);
alter table only "public"."journal_quality" add constraint "journal_quality_cas_zone_check" CHECK (cas_zone = ANY (ARRAY['1区'::text, '2区'::text, '3区'::text, '4区'::text]));
alter table only "public"."journal_quality" add constraint "journal_quality_es_sync_status_check" CHECK (es_sync_status = ANY (ARRAY['success'::text, 'failed'::text, 'not_found'::text]));
alter table only "public"."journal_quality" add constraint "journal_quality_jcr_quartile_check" CHECK (jcr_quartile = ANY (ARRAY['Q1'::text, 'Q2'::text, 'Q3'::text, 'Q4'::text]));
alter table only "public"."journal_quality" add constraint "journal_quality_tier_check" CHECK (tier = ANY (ARRAY['top'::text, 'core'::text, 'emerging'::text]));
alter table only "public"."journal_quality" add constraint "journal_quality_pkey" PRIMARY KEY (id);
alter table only "public"."journal_quality" add constraint "journal_quality_journal_name_key" UNIQUE (journal_name);
alter table only "public"."journal_sync_log" add constraint "journal_sync_log_status_check" CHECK (status = ANY (ARRAY['success'::text, 'failed'::text, 'running'::text]));
alter table only "public"."journal_sync_log" add constraint "journal_sync_log_journal_quality_id_fkey" FOREIGN KEY (journal_quality_id) REFERENCES journal_quality(id) ON DELETE CASCADE;
alter table only "public"."journal_sync_log" add constraint "journal_sync_log_pkey" PRIMARY KEY (id);
alter table only "public"."keyword_synonyms" add constraint "keyword_synonyms_source_check" CHECK (source = ANY (ARRAY['manual'::text, 'llm'::text, 'merged'::text]));
alter table only "public"."keyword_synonyms" add constraint "keyword_synonyms_pkey" PRIMARY KEY (id);
alter table only "public"."keyword_synonyms" add constraint "keyword_synonyms_canonical_keyword_key" UNIQUE (canonical_keyword);
alter table only "public"."paper_research_topics" add constraint "paper_research_topics_paper_id_fkey" FOREIGN KEY (paper_id) REFERENCES papers(id) ON DELETE CASCADE;
alter table only "public"."paper_research_topics" add constraint "paper_research_topics_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES research_topics(id) ON DELETE CASCADE;
alter table only "public"."paper_research_topics" add constraint "paper_research_topics_pkey" PRIMARY KEY (paper_id, topic_id);
alter table only "public"."paper_topics" add constraint "paper_topics_paper_id_fkey" FOREIGN KEY (paper_id) REFERENCES papers(id) ON DELETE CASCADE;
alter table only "public"."paper_topics" add constraint "paper_topics_pkey" PRIMARY KEY (paper_id, topic);
alter table only "public"."papers" add constraint "papers_quality_tier_check" CHECK (quality_tier = ANY (ARRAY['top'::text, 'core'::text, 'emerging'::text]));
alter table only "public"."papers" add constraint "papers_pkey" PRIMARY KEY (id);
alter table only "public"."papers" add constraint "papers_pmid_key" UNIQUE (pmid);
alter table only "public"."profiles" add constraint "profiles_byok_provider_check" CHECK (byok_provider = ANY (ARRAY['openai'::text, 'anthropic'::text, 'deepseek'::text, 'gemini'::text, 'zhipu'::text, 'moonshot'::text, 'qwen'::text]));
alter table only "public"."profiles" add constraint "profiles_role_check" CHECK (role = ANY (ARRAY['doctor'::text, 'admin'::text, 'researcher'::text]));
alter table only "public"."profiles" add constraint "profiles_weekly_digest_day_check" CHECK (weekly_digest_day >= 0 AND weekly_digest_day <= 6);
alter table only "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY (id);
alter table only "public"."push_issue_items" add constraint "push_issue_items_issue_id_fkey" FOREIGN KEY (issue_id) REFERENCES push_issues(id) ON DELETE CASCADE;
alter table only "public"."push_issue_items" add constraint "push_issue_items_paper_id_fkey" FOREIGN KEY (paper_id) REFERENCES papers(id) ON DELETE CASCADE;
alter table only "public"."push_issue_items" add constraint "push_issue_items_pkey" PRIMARY KEY (issue_id, paper_id);
alter table only "public"."push_issues" add constraint "push_issues_status_check" CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'failed'::text]));
alter table only "public"."push_issues" add constraint "push_issues_pkey" PRIMARY KEY (id);
alter table only "public"."push_issues" add constraint "push_issues_issue_week_start_key" UNIQUE (issue_week_start);
alter table only "public"."research_topics" add constraint "research_topics_pkey" PRIMARY KEY (id);
alter table only "public"."research_topics" add constraint "research_topics_slug_key" UNIQUE (slug);
alter table only "public"."subject_categories" add constraint "subject_categories_source_check" CHECK (source = ANY (ARRAY['manual'::text, 'jcr'::text, 'xinrui'::text, 'auto'::text]));
alter table only "public"."subject_categories" add constraint "subject_categories_pkey" PRIMARY KEY (id);
alter table only "public"."sync_state" add constraint "sync_state_pkey" PRIMARY KEY (key);
alter table only "public"."user_journal_subscriptions" add constraint "user_journal_subscriptions_journal_quality_id_fkey" FOREIGN KEY (journal_quality_id) REFERENCES journal_quality(id) ON DELETE CASCADE;
alter table only "public"."user_journal_subscriptions" add constraint "user_journal_subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only "public"."user_journal_subscriptions" add constraint "user_journal_subscriptions_pkey" PRIMARY KEY (user_id, journal_quality_id);
alter table only "public"."user_paper_interactions" add constraint "user_paper_interactions_paper_id_fkey" FOREIGN KEY (paper_id) REFERENCES papers(id) ON DELETE CASCADE;
alter table only "public"."user_paper_interactions" add constraint "user_paper_interactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only "public"."user_paper_interactions" add constraint "user_paper_interactions_pkey" PRIMARY KEY (id);
alter table only "public"."user_paper_interactions" add constraint "user_paper_interactions_user_id_paper_id_key" UNIQUE (user_id, paper_id);
alter table only "public"."user_topic_subscriptions" add constraint "user_topic_subscriptions_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES research_topics(id) ON DELETE CASCADE;
alter table only "public"."user_topic_subscriptions" add constraint "user_topic_subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only "public"."user_topic_subscriptions" add constraint "user_topic_subscriptions_pkey" PRIMARY KEY (user_id, topic_id);
alter table only "public"."user_weekly_push_deliveries" add constraint "user_weekly_push_deliveries_issue_id_fkey" FOREIGN KEY (issue_id) REFERENCES push_issues(id) ON DELETE CASCADE;
alter table only "public"."user_weekly_push_deliveries" add constraint "user_weekly_push_deliveries_paper_id_fkey" FOREIGN KEY (paper_id) REFERENCES papers(id) ON DELETE CASCADE;
alter table only "public"."user_weekly_push_deliveries" add constraint "user_weekly_push_deliveries_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only "public"."user_weekly_push_deliveries" add constraint "user_weekly_push_deliveries_pkey" PRIMARY KEY (id);
alter table only "public"."user_weekly_push_deliveries" add constraint "user_weekly_push_deliveries_issue_user_paper_key" UNIQUE (issue_id, user_id, paper_id);
alter table only "public"."user_weekly_push_deliveries" add constraint "user_weekly_push_deliveries_user_paper_key" UNIQUE (user_id, paper_id);
alter table only "public"."user_weekly_spotlight_deliveries" add constraint "user_weekly_spotlight_deliveries_status_check" CHECK (status = ANY (ARRAY['processing'::text, 'sent'::text, 'failed'::text]));
alter table only "public"."user_weekly_spotlight_deliveries" add constraint "user_weekly_spotlight_deliveries_trigger_source_check" CHECK (trigger_source = ANY (ARRAY['cron'::text, 'manual'::text]));
alter table only "public"."user_weekly_spotlight_deliveries" add constraint "user_weekly_spotlight_deliveries_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only "public"."user_weekly_spotlight_deliveries" add constraint "user_weekly_spotlight_deliveries_pkey" PRIMARY KEY (id);
alter table only "public"."user_weekly_spotlight_deliveries" add constraint "user_weekly_spotlight_deliveries_user_id_issue_week_start_key" UNIQUE (user_id, issue_week_start);
alter table only "public"."weekly_reports" add constraint "weekly_reports_email_status_check" CHECK (email_status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'skipped'::text]));
alter table only "public"."weekly_reports" add constraint "weekly_reports_crossover_paper_id_fkey" FOREIGN KEY (crossover_paper_id) REFERENCES papers(id);
alter table only "public"."weekly_reports" add constraint "weekly_reports_hotspot_paper_id_fkey" FOREIGN KEY (hotspot_paper_id) REFERENCES papers(id);
alter table only "public"."weekly_reports" add constraint "weekly_reports_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only "public"."weekly_reports" add constraint "weekly_reports_pkey" PRIMARY KEY (id);
alter table only "public"."weekly_reports" add constraint "weekly_reports_user_id_period_from_period_to_key" UNIQUE (user_id, period_from, period_to);

-- Functions and RPCs
CREATE OR REPLACE FUNCTION public.build_pubmed_query_for_keyword(p_keyword text, p_days_back integer DEFAULT 7)
 RETURNS text
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_template text;
  v_synonyms text[];
  v_english_terms text[] := '{}';
  v_date_from text := to_char(current_date - p_days_back, 'YYYY/MM/DD');
  v_date_to text := to_char(current_date, 'YYYY/MM/DD');
  v_term text;
  v_ai_part text := '("Artificial Intelligence"[Mesh] OR "Machine Learning"[Mesh] OR "Deep Learning"[Mesh] OR "Neural Networks, Computer"[Mesh] OR "artificial intelligence"[Title/Abstract] OR "machine learning"[Title/Abstract] OR "deep learning"[Title/Abstract] OR "neural network*"[Title/Abstract] OR "natural language processing"[Title/Abstract] OR "large language model*"[Title/Abstract] OR "foundation model*"[Title/Abstract])';
  v_med_part text;
BEGIN
  -- 优先查缓存的完整检索式
  SELECT pubmed_query_template, synonyms 
  INTO v_template, v_synonyms
  FROM keyword_synonyms 
  WHERE lower(canonical_keyword) = lower(p_keyword)
  LIMIT 1;

  -- 如果有 LLM 生成的专业检索式模板，直接用
  IF v_template IS NOT NULL AND v_template != '' THEN
    RETURN v_ai_part || ' AND ' || v_template || ' AND ' || v_date_from || ':' || v_date_to || '[dp]';
  END IF;

  -- 退化逻辑：用同义词拼接（兼容旧数据）
  IF v_synonyms IS NOT NULL THEN
    FOREACH v_term IN ARRAY v_synonyms LOOP
      IF v_term ~ '^[a-zA-Z0-9 /&''-]+$' THEN
        v_english_terms := v_english_terms || ARRAY[v_term];
      END IF;
    END LOOP;
  ELSE
    v_english_terms := ARRAY[p_keyword];
  END IF;

  v_med_part := '(' || array_to_string(
    ARRAY(SELECT '"' || t || '"[Title/Abstract]' FROM unnest(v_english_terms) AS t),
    ' OR '
  ) || ')';

  RETURN v_ai_part || ' AND ' || v_med_part || ' AND ' || v_date_from || ':' || v_date_to || '[dp]';
END;
$function$

CREATE OR REPLACE FUNCTION public.calculate_ai_med_score(p_title text, p_abstract text DEFAULT ''::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_title text := ' ' || lower(coalesce(p_title, '')) || ' ';
  v_abstract text := ' ' || lower(coalesce(p_abstract, '')) || ' ';
  v_score numeric := 0;
  v_reasons text[] := '{}';
  v_ai_strong text[] := ARRAY[
    'deep learning', 'machine learning', 'artificial intelligence',
    'neural network', 'convolutional neural', 'recurrent neural',
    'reinforcement learning', 'federated learning',
    'natural language processing', 'computer vision',
    'image segmentation', 'object detection',
    'deep neural', 'graph neural',
    'transformer', 'large language model', 'llm', 'foundation model',
    'vision-language', 'vision language', 'multimodal model',
    'generative ai', 'chatgpt', 'gpt-4', 'gpt4', 'gpt-3',
    'bert', 'attention mechanism', 'self-supervised',
    'diffusion model', 'autoencoder', 'variational autoencoder',
    'contrastive learning', 'self-supervised learning',
    'few-shot', 'zero-shot', 'transfer learning',
    'pre-training', 'pretraining', 'fine-tuning', 'finetuning',
    'prompt learning', 'prompt tuning',
    'vision transformer', 'vit ', 'swin transformer',
    'u-net', 'unet', 'resnet', 'densenet', 'efficientnet',
    'clip ', 'sam ', 'segment anything',
    'generative adversarial', 'gan ', 'gans ',
    'ai-based', 'ai-driven', 'ai-enabled', 'ai-powered',
    'ai-assisted', 'ai-derived', 'ai-enhanced', 'ai-guided', 'ai-augmented',
    'ai model', 'ai system', 'ai tool',
    ' ai ', ' ai.', ' ai,', ' ai:', ' ai;', '-ai '
  ];
  v_ai_weak text[] := ARRAY[
    'prediction model', 'predictive model', 'predictive modeling',
    'classification model', 'regression model',
    'clustering', 'random forest', 'xgboost', 'gradient boosting',
    'support vector', 'logistic regression', 'decision tree',
    'feature selection', 'feature extraction',
    'automated', 'computational', 'algorithm',
    'radiomics', 'radiogenomics', 'pathomics',
    'nomogram', 'risk score', 'scoring system'
  ];
  v_med_strong text[] := ARRAY[
    'clinical', 'patient', 'diagnosis', 'prognosis',
    'treatment', 'therapy', 'surgery', 'surgical',
    'cancer', 'tumor', 'tumour', 'oncology', 'carcinoma', 'malignancy',
    'disease', 'disorder', 'syndrome',
    'hospital', 'icu', 'emergency', 'mortality',
    'radiology', 'pathology', 'histopathology',
    'mri', 'ct scan', 'x-ray', 'ultrasound', 'echocardiography',
    'ehr', 'electronic health record', 'medical record',
    'drug', 'pharmaceutical', 'biomarker',
    'genomic', 'proteomic', 'transcriptomic',
    'cardiac', 'cardiovascular', 'pulmonary', 'neurological',
    'ophthalmology', 'dermatology', 'gastroenterology',
    'pediatric', 'geriatric', 'obstetric',
    'medical imaging', 'digital pathology',
    'clinical trial', 'cohort study', 'randomized',
    'screening', 'detection', 'early detection',
    'survival', 'recurrence', 'metastasis',
    'precision medicine', 'personalized medicine',
    'lung', 'breast', 'colon', 'liver', 'brain',
    'kidney', 'prostate', 'thyroid', 'skin',
    'nodule', 'lesion', 'polyp',
    'biopsy', 'specimen', 'tissue',
    'ct ', 'pet ', 'pet/ct', 'mammograph', 'endoscop',
    'sepsis', 'stroke', 'fracture', 'hemorrhage'
  ];
  v_ai_title_strong int := 0; v_ai_title_weak int := 0;
  v_ai_abs_strong int := 0; v_ai_abs_weak int := 0;
  v_med_title int := 0; v_med_abs int := 0;
  v_kw text;
BEGIN
  FOREACH v_kw IN ARRAY v_ai_strong LOOP
    IF v_title LIKE '%' || v_kw || '%' THEN v_ai_title_strong := v_ai_title_strong + 1; END IF;
  END LOOP;
  FOREACH v_kw IN ARRAY v_ai_weak LOOP
    IF v_title LIKE '%' || v_kw || '%' THEN v_ai_title_weak := v_ai_title_weak + 1; END IF;
  END LOOP;
  FOREACH v_kw IN ARRAY v_ai_strong LOOP
    IF v_abstract LIKE '%' || v_kw || '%' THEN v_ai_abs_strong := v_ai_abs_strong + 1; END IF;
  END LOOP;
  FOREACH v_kw IN ARRAY v_ai_weak LOOP
    IF v_abstract LIKE '%' || v_kw || '%' THEN v_ai_abs_weak := v_ai_abs_weak + 1; END IF;
  END LOOP;
  FOREACH v_kw IN ARRAY v_med_strong LOOP
    IF v_title LIKE '%' || v_kw || '%' THEN v_med_title := v_med_title + 1; END IF;
  END LOOP;
  FOREACH v_kw IN ARRAY v_med_strong LOOP
    IF v_abstract LIKE '%' || v_kw || '%' THEN v_med_abs := v_med_abs + 1; END IF;
  END LOOP;

  v_score := v_score + least(v_ai_title_strong * 0.15, 0.45);
  v_score := v_score + least(v_ai_title_weak * 0.05, 0.10);
  v_score := v_score + least(v_ai_abs_strong * 0.04, 0.16);
  v_score := v_score + least(v_ai_abs_weak * 0.02, 0.06);
  v_score := v_score + least(v_med_title * 0.08, 0.24);
  v_score := v_score + least(v_med_abs * 0.02, 0.10);

  IF (v_ai_title_strong > 0 OR v_ai_title_weak > 0) AND v_med_title > 0 THEN
    v_score := v_score + 0.10;
    v_reasons := array_append(v_reasons, 'title_cross_hit');
  END IF;

  v_score := least(v_score, 1.0);
  v_score := round(v_score, 4);

  IF v_ai_title_strong > 0 THEN v_reasons := array_append(v_reasons, 'ai_strong_in_title:' || v_ai_title_strong); END IF;
  IF v_med_title > 0 THEN v_reasons := array_append(v_reasons, 'med_in_title:' || v_med_title); END IF;

  -- 放宽判定规则：
  -- 条件 A：分数 >= 0.35 且标题有 AI 关键词（强或弱）— 原规则
  -- 条件 B：分数 >= 0.40 且摘要有 ≥2 个 AI 强关键词 — 新增（覆盖标题不提 AI 但方法用了 AI 的论文）
  RETURN jsonb_build_object(
    'score', v_score,
    'is_ai_med', (
      (v_score >= 0.35 AND (v_ai_title_strong > 0 OR v_ai_title_weak > 0))
      OR (v_score >= 0.40 AND v_ai_abs_strong >= 2)
    ),
    'ai_title_strong', v_ai_title_strong,
    'ai_title_weak', v_ai_title_weak,
    'ai_abs_strong', v_ai_abs_strong,
    'med_title', v_med_title,
    'med_abs', v_med_abs,
    'reasons', to_jsonb(v_reasons)
  );
END;
$function$

CREATE OR REPLACE PROCEDURE public.db_sync_all_journals(IN p_days_back integer DEFAULT 30, IN p_only_missing boolean DEFAULT false)
 LANGUAGE plpgsql
AS $procedure$
DECLARE
  v_journal record;
  v_result jsonb;
BEGIN
  FOR v_journal IN 
    SELECT jq.id, jq.journal_name, COUNT(p.id) AS paper_count
    FROM journal_quality jq
    LEFT JOIN papers p ON (lower(p.journal) = lower(jq.journal_name) OR 
                           EXISTS (SELECT 1 FROM unnest(jq.aliases) a WHERE lower(a) = lower(p.journal)))
    WHERE jq.is_active = true
    GROUP BY jq.id, jq.journal_name
    HAVING (NOT p_only_missing OR COUNT(p.id) = 0)
    ORDER BY COUNT(p.id) ASC  -- 优先同步论文最少的期刊
  LOOP
    BEGIN
      CALL db_sync_one_journal(v_journal.id, p_days_back, v_result);
      RAISE NOTICE '同步 % 完成: %', v_journal.journal_name, v_result;
      PERFORM pg_sleep(2);  -- PubMed rate limit 防护
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE '同步 % 失败: %', v_journal.journal_name, SQLERRM;
    END;
  END LOOP;
END;
$procedure$

CREATE OR REPLACE PROCEDURE public.db_sync_one_journal(IN p_journal_quality_id uuid, IN p_days_back integer DEFAULT 30, INOUT p_result jsonb DEFAULT NULL::jsonb)
 LANGUAGE plpgsql
AS $procedure$
DECLARE
  v_journal_name text;
  v_weight numeric;
  v_if numeric;
  v_jcr text;
  v_cas text;
  v_date_from text := to_char(current_date - p_days_back, 'YYYY/MM/DD');
  v_date_to text := to_char(current_date, 'YYYY/MM/DD');
  v_search_req_id bigint;
  v_fetch_req_id bigint;
  v_search_content jsonb;
  v_fetch_content xml;
  v_pmids text[];
  v_new_pmids text[];
  v_papers_found int := 0;
  v_papers_passed int := 0;
  v_papers_new int := 0;
  v_inserted int;
  v_log_id uuid;
  v_query_url text;
  v_article xml;
  v_pmid text;
  v_title text;
  v_journal_xml text;
  v_abstract text;
  v_pub_year text;
  v_pub_month text;
  v_pub_day text;
  v_pub_date date;
  v_score jsonb;
  v_ai_score numeric;
  v_is_ai_med boolean;
  v_final_tier text;
  v_quality_score numeric;
  v_retries int;
BEGIN
  SELECT journal_name, weight, impact_factor, jcr_quartile, cas_zone
  INTO v_journal_name, v_weight, v_if, v_jcr, v_cas
  FROM journal_quality WHERE id = p_journal_quality_id;
  
  IF v_journal_name IS NULL THEN
    p_result := jsonb_build_object('status', 'error', 'reason', 'journal_not_found');
    RETURN;
  END IF;
  
  INSERT INTO journal_sync_log (
    journal_quality_id, journal_name, sync_from, sync_to, status
  ) VALUES (
    p_journal_quality_id, v_journal_name, 
    current_date - p_days_back, current_date, 'running'
  ) RETURNING id INTO v_log_id;
  COMMIT;
  
  v_query_url := 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=' ||
    url_encode_pubmed('"' || v_journal_name || '"[Journal] AND ' || v_date_from || ':' || v_date_to || '[dp]') ||
    '&retmax=100&retmode=json';
  
  SELECT net.http_get(v_query_url) INTO v_search_req_id;
  COMMIT;
  
  v_retries := 0;
  WHILE v_retries < 20 LOOP
    PERFORM pg_sleep(1);
    SELECT content::jsonb INTO v_search_content FROM net._http_response WHERE id = v_search_req_id;
    EXIT WHEN v_search_content IS NOT NULL;
    v_retries := v_retries + 1;
  END LOOP;
  
  IF v_search_content IS NULL THEN
    UPDATE journal_sync_log SET status='failed', error_message='esearch 20s 无响应', finished_at=now() WHERE id = v_log_id;
    p_result := jsonb_build_object('status', 'failed', 'reason', 'esearch_timeout');
    RETURN;
  END IF;
  
  SELECT array_agg(value) INTO v_pmids FROM jsonb_array_elements_text(v_search_content->'esearchresult'->'idlist');
  v_papers_found := COALESCE(array_length(v_pmids, 1), 0);
  
  IF v_papers_found = 0 THEN
    UPDATE journal_sync_log SET status='success', papers_found=0, finished_at=now() WHERE id = v_log_id;
    p_result := jsonb_build_object('status', 'success', 'papers_found', 0);
    RETURN;
  END IF;
  
  SELECT array_agg(p) INTO v_new_pmids FROM unnest(v_pmids) AS p WHERE NOT EXISTS (SELECT 1 FROM papers WHERE pmid = p);
  
  IF COALESCE(array_length(v_new_pmids, 1), 0) = 0 THEN
    UPDATE journal_sync_log SET status='success', papers_found=v_papers_found, finished_at=now() WHERE id = v_log_id;
    p_result := jsonb_build_object('status', 'success', 'papers_found', v_papers_found, 'all_exist', true);
    RETURN;
  END IF;
  
  SELECT net.http_get(
    'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=' ||
    array_to_string(v_new_pmids, ',') || '&retmode=xml'
  ) INTO v_fetch_req_id;
  COMMIT;
  
  v_retries := 0;
  WHILE v_retries < 30 LOOP
    PERFORM pg_sleep(1);
    SELECT content::xml INTO v_fetch_content FROM net._http_response WHERE id = v_fetch_req_id;
    EXIT WHEN v_fetch_content IS NOT NULL;
    v_retries := v_retries + 1;
  END LOOP;
  
  IF v_fetch_content IS NULL THEN
    UPDATE journal_sync_log SET status='failed', error_message='efetch 30s 无响应', papers_found=v_papers_found, finished_at=now() WHERE id = v_log_id;
    p_result := jsonb_build_object('status', 'failed', 'reason', 'efetch_timeout');
    RETURN;
  END IF;
  
  FOR v_article IN SELECT unnest(xpath('/PubmedArticleSet/PubmedArticle', v_fetch_content))
  LOOP
    BEGIN
      v_pmid := (xpath('//PMID[1]/text()', v_article))[1]::text;
      v_title := (xpath('//ArticleTitle/text()', v_article))[1]::text;
      v_journal_xml := (xpath('//Journal/Title/text()', v_article))[1]::text;
      
      SELECT string_agg(t::text, E'\n') INTO v_abstract FROM unnest(xpath('//Abstract/AbstractText/text()', v_article)) t;
      
      v_pub_year := COALESCE((xpath('//ArticleDate[1]/Year/text()', v_article))[1]::text, (xpath('//PubDate/Year/text()', v_article))[1]::text, to_char(current_date, 'YYYY'));
      v_pub_month := COALESCE((xpath('//ArticleDate[1]/Month/text()', v_article))[1]::text, (xpath('//PubDate/Month/text()', v_article))[1]::text, '01');
      v_pub_day := COALESCE((xpath('//ArticleDate[1]/Day/text()', v_article))[1]::text, (xpath('//PubDate/Day/text()', v_article))[1]::text, '01');
      
      v_pub_month := CASE lower(v_pub_month)
        WHEN 'jan' THEN '01' WHEN 'feb' THEN '02' WHEN 'mar' THEN '03'
        WHEN 'apr' THEN '04' WHEN 'may' THEN '05' WHEN 'jun' THEN '06'
        WHEN 'jul' THEN '07' WHEN 'aug' THEN '08' WHEN 'sep' THEN '09'
        WHEN 'oct' THEN '10' WHEN 'nov' THEN '11' WHEN 'dec' THEN '12'
        ELSE v_pub_month END;
      
      BEGIN
        v_pub_date := to_date(v_pub_year || '-' || v_pub_month || '-' || v_pub_day, 'YYYY-MM-DD');
      EXCEPTION WHEN OTHERS THEN
        v_pub_date := to_date(v_pub_year || '-01-01', 'YYYY-MM-DD');
      END;
      
      v_score := calculate_ai_med_score(v_title, COALESCE(v_abstract, ''));
      v_ai_score := (v_score->>'score')::numeric;
      v_is_ai_med := (v_score->>'is_ai_med')::boolean;
      
      IF v_is_ai_med THEN v_papers_passed := v_papers_passed + 1; END IF;
      
      v_final_tier := CASE WHEN v_weight >= 0.9 THEN 'top' WHEN v_weight >= 0.7 THEN 'core' ELSE 'emerging' END;
      v_quality_score := round((v_ai_score * v_weight)::numeric, 4);
      
      INSERT INTO papers (
        pmid, title, abstract, journal, publication_date,
        pubmed_url, is_open_access,
        ai_med_score, is_ai_med, quality_tier, quality_score,
        journal_if, journal_jcr, journal_cas_zone
      ) VALUES (
        v_pmid, v_title, v_abstract, COALESCE(v_journal_xml, v_journal_name), v_pub_date,
        'https://pubmed.ncbi.nlm.nih.gov/' || v_pmid || '/', false,
        v_ai_score, 
        CASE WHEN v_final_tier = 'emerging' THEN false ELSE v_is_ai_med END,
        v_final_tier, v_quality_score, v_if, v_jcr, v_cas
      ) ON CONFLICT (pmid) DO NOTHING;
      
      GET DIAGNOSTICS v_inserted = ROW_COUNT;
      v_papers_new := v_papers_new + v_inserted;  -- 累加而不是覆盖
    EXCEPTION WHEN OTHERS THEN CONTINUE;
    END;
  END LOOP;
  
  UPDATE journal_sync_log SET 
    status='success', papers_found=v_papers_found, papers_passed=v_papers_passed,
    papers_new=v_papers_new, finished_at=now()
  WHERE id = v_log_id;
  
  DELETE FROM net._http_response WHERE id IN (v_search_req_id, v_fetch_req_id);
  
  p_result := jsonb_build_object(
    'status', 'success', 'journal', v_journal_name,
    'papers_found', v_papers_found, 'papers_new', v_papers_new, 'papers_passed', v_papers_passed
  );
END;
$procedure$

CREATE OR REPLACE FUNCTION public.db_sync_one_journal(p_journal_quality_id uuid, p_days_back integer DEFAULT 30)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_journal_name text;
  v_aliases text[];
  v_weight numeric;
  v_tier text;
  v_if numeric;
  v_jcr text;
  v_cas text;
  v_date_from text := to_char(current_date - p_days_back, 'YYYY/MM/DD');
  v_date_to text := to_char(current_date, 'YYYY/MM/DD');
  v_search_req_id bigint;
  v_fetch_req_id bigint;
  v_search_content jsonb;
  v_fetch_content xml;
  v_pmids text[];
  v_new_pmids text[];
  v_papers_found int := 0;
  v_papers_passed int := 0;
  v_papers_new int := 0;
  v_log_id uuid;
  v_query_url text;
  v_article xml;
  v_pmid text;
  v_title text;
  v_journal_xml text;
  v_abstract text;
  v_pub_year text;
  v_pub_month text;
  v_pub_day text;
  v_pub_date date;
  v_score jsonb;
  v_ai_score numeric;
  v_is_ai_med boolean;
  v_final_tier text;
  v_quality_score numeric;
BEGIN
  -- 读取期刊信息
  SELECT journal_name, aliases, weight, tier, impact_factor, jcr_quartile, cas_zone
  INTO v_journal_name, v_aliases, v_weight, v_tier, v_if, v_jcr, v_cas
  FROM journal_quality WHERE id = p_journal_quality_id;
  
  IF v_journal_name IS NULL THEN
    RETURN jsonb_build_object('status', 'error', 'reason', 'journal_not_found');
  END IF;
  
  -- 创建日志
  INSERT INTO journal_sync_log (
    journal_quality_id, journal_name, sync_from, sync_to, status
  ) VALUES (
    p_journal_quality_id, v_journal_name, 
    current_date - p_days_back, current_date, 'running'
  ) RETURNING id INTO v_log_id;
  
  -- Step 1: esearch
  v_query_url := 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=' ||
    url_encode_pubmed('"' || v_journal_name || '"[Journal] AND ' || v_date_from || ':' || v_date_to || '[dp]') ||
    '&retmax=50&retmode=json';
  
  SELECT net.http_get(v_query_url) INTO v_search_req_id;
  
  -- 等 PubMed 响应
  PERFORM pg_sleep(5);
  
  SELECT content::jsonb INTO v_search_content FROM net._http_response WHERE id = v_search_req_id;
  
  IF v_search_content IS NULL THEN
    UPDATE journal_sync_log SET 
      status='failed', error_message='esearch 5s 无响应', finished_at=now() 
    WHERE id = v_log_id;
    RETURN jsonb_build_object('status', 'failed', 'reason', 'esearch_timeout', 'url', v_query_url);
  END IF;
  
  -- 提取 PMID
  SELECT array_agg(value) INTO v_pmids
  FROM jsonb_array_elements_text(v_search_content->'esearchresult'->'idlist');
  
  v_papers_found := COALESCE(array_length(v_pmids, 1), 0);
  
  IF v_papers_found = 0 THEN
    UPDATE journal_sync_log SET 
      status='success', papers_found=0, finished_at=now()
    WHERE id = v_log_id;
    RETURN jsonb_build_object('status', 'success', 'papers_found', 0);
  END IF;
  
  -- 过滤已存在的 PMID
  SELECT array_agg(p) INTO v_new_pmids
  FROM unnest(v_pmids) AS p
  WHERE NOT EXISTS (SELECT 1 FROM papers WHERE pmid = p);
  
  IF COALESCE(array_length(v_new_pmids, 1), 0) = 0 THEN
    UPDATE journal_sync_log SET 
      status='success', papers_found=v_papers_found, finished_at=now()
    WHERE id = v_log_id;
    RETURN jsonb_build_object('status', 'success', 'papers_found', v_papers_found, 'all_exist', true);
  END IF;
  
  -- Step 2: efetch XML
  SELECT net.http_get(
    'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=' ||
    array_to_string(v_new_pmids, ',') || '&retmode=xml'
  ) INTO v_fetch_req_id;
  
  PERFORM pg_sleep(10);
  
  SELECT content::xml INTO v_fetch_content FROM net._http_response WHERE id = v_fetch_req_id;
  
  IF v_fetch_content IS NULL THEN
    UPDATE journal_sync_log SET 
      status='failed', error_message='efetch 10s 无响应',
      papers_found=v_papers_found, finished_at=now()
    WHERE id = v_log_id;
    RETURN jsonb_build_object('status', 'failed', 'reason', 'efetch_timeout');
  END IF;
  
  -- Step 3: 逐篇解析 + 评分 + 入库
  FOR v_article IN
    SELECT unnest(xpath('/PubmedArticleSet/PubmedArticle', v_fetch_content))
  LOOP
    BEGIN
      v_pmid := (xpath('//PMID[1]/text()', v_article))[1]::text;
      v_title := (xpath('//ArticleTitle/text()', v_article))[1]::text;
      v_journal_xml := (xpath('//Journal/Title/text()', v_article))[1]::text;
      
      -- 摘要可能有多段（BACKGROUND/METHODS/RESULTS 等）
      SELECT string_agg(t::text, E'\n') INTO v_abstract
      FROM unnest(xpath('//Abstract/AbstractText/text()', v_article)) t;
      
      -- 发表日期：优先 ArticleDate（电子出版日期），回退 PubDate
      v_pub_year := COALESCE(
        (xpath('//ArticleDate[1]/Year/text()', v_article))[1]::text,
        (xpath('//PubDate/Year/text()', v_article))[1]::text,
        to_char(current_date, 'YYYY')
      );
      v_pub_month := COALESCE(
        (xpath('//ArticleDate[1]/Month/text()', v_article))[1]::text,
        (xpath('//PubDate/Month/text()', v_article))[1]::text,
        '01'
      );
      v_pub_day := COALESCE(
        (xpath('//ArticleDate[1]/Day/text()', v_article))[1]::text,
        (xpath('//PubDate/Day/text()', v_article))[1]::text,
        '01'
      );
      
      -- 月份可能是英文简写（如 "Mar"）
      v_pub_month := CASE lower(v_pub_month)
        WHEN 'jan' THEN '01' WHEN 'feb' THEN '02' WHEN 'mar' THEN '03'
        WHEN 'apr' THEN '04' WHEN 'may' THEN '05' WHEN 'jun' THEN '06'
        WHEN 'jul' THEN '07' WHEN 'aug' THEN '08' WHEN 'sep' THEN '09'
        WHEN 'oct' THEN '10' WHEN 'nov' THEN '11' WHEN 'dec' THEN '12'
        ELSE v_pub_month
      END;
      
      BEGIN
        v_pub_date := to_date(v_pub_year || '-' || v_pub_month || '-' || v_pub_day, 'YYYY-MM-DD');
      EXCEPTION WHEN OTHERS THEN
        v_pub_date := to_date(v_pub_year || '-01-01', 'YYYY-MM-DD');
      END;
      
      -- 评分
      v_score := calculate_ai_med_score(v_title, COALESCE(v_abstract, ''));
      v_ai_score := (v_score->>'score')::numeric;
      v_is_ai_med := (v_score->>'is_ai_med')::boolean;
      
      IF v_is_ai_med THEN v_papers_passed := v_papers_passed + 1; END IF;
      
      -- 计算 quality tier/score
      v_final_tier := CASE 
        WHEN v_weight >= 0.9 THEN 'top'
        WHEN v_weight >= 0.7 THEN 'core'
        ELSE 'emerging'
      END;
      v_quality_score := round((v_ai_score * v_weight)::numeric, 4);
      
      -- 入库
      INSERT INTO papers (
        pmid, title, abstract, journal, publication_date,
        pubmed_url, is_open_access,
        ai_med_score, is_ai_med, quality_tier, quality_score,
        journal_if, journal_jcr, journal_cas_zone
      ) VALUES (
        v_pmid, v_title, v_abstract, COALESCE(v_journal_xml, v_journal_name), v_pub_date,
        'https://pubmed.ncbi.nlm.nih.gov/' || v_pmid || '/', false,
        v_ai_score, 
        -- emerging 的论文强制 is_ai_med=false（我们现有策略）
        CASE WHEN v_final_tier = 'emerging' THEN false ELSE v_is_ai_med END,
        v_final_tier, v_quality_score,
        v_if, v_jcr, v_cas
      ) ON CONFLICT (pmid) DO NOTHING;
      
      IF FOUND THEN v_papers_new := v_papers_new + 1; END IF;
    EXCEPTION WHEN OTHERS THEN
      -- 单篇失败不影响整批
      CONTINUE;
    END;
  END LOOP;
  
  -- 写日志
  UPDATE journal_sync_log SET 
    status='success', 
    papers_found=v_papers_found, 
    papers_passed=v_papers_passed,
    papers_new=v_papers_new,
    finished_at=now()
  WHERE id = v_log_id;
  
  -- 清理本次的 http 响应（节省空间）
  DELETE FROM net._http_response WHERE id IN (v_search_req_id, v_fetch_req_id);
  
  RETURN jsonb_build_object(
    'status', 'success',
    'journal', v_journal_name,
    'papers_found', v_papers_found,
    'papers_new', v_papers_new,
    'papers_passed', v_papers_passed
  );
END;
$function$

CREATE OR REPLACE FUNCTION public.generate_weekly_digest(p_user_id uuid, p_days_back integer DEFAULT 7)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_keywords text[];
  v_journals text[];
  v_expanded_synonyms text[] := '{}';
  v_title_required text[] := '{}';
  v_specialty_papers jsonb;
  v_hotspot_paper jsonb;
  v_crossover_paper jsonb;
  v_specialty_ids uuid[];
  v_period_from date := current_date - p_days_back;
  v_period_to date := current_date;
  v_kw text;
BEGIN
  -- 读取用户偏好
  SELECT subscription_keywords, custom_journals
  INTO v_keywords, v_journals
  FROM profiles WHERE id = p_user_id;

  -- 扩展同义词（与 Feed 函数一致）
  IF v_keywords IS NOT NULL AND array_length(v_keywords, 1) > 0 THEN
    FOREACH v_kw IN ARRAY v_keywords LOOP
      DECLARE v_syn text[]; v_req text[];
      BEGIN
        SELECT synonyms, title_required INTO v_syn, v_req
        FROM keyword_synonyms WHERE lower(canonical_keyword) = lower(v_kw) LIMIT 1;
        IF v_syn IS NOT NULL THEN
          v_expanded_synonyms := v_expanded_synonyms || v_syn;
          v_title_required := v_title_required || v_req;
        ELSE
          v_expanded_synonyms := v_expanded_synonyms || ARRAY[v_kw];
          v_title_required := v_title_required || ARRAY[v_kw];
        END IF;
      END;
    END LOOP;
  END IF;

  -- ========================================
  -- 专科论文：严格匹配关键词 + 严格 7 天窗口
  -- 能找到几篇就是几篇，上限 5 篇
  -- ========================================
  WITH specialty AS (
    SELECT p.id, p.title, p.title_zh, p.abstract_zh, p.journal, p.journal_if,
           p.journal_jcr, p.journal_cas_zone, p.publication_date, p.pubmed_url,
           p.quality_score, p.recommendation_reason,
           (p.quality_score * CASE
              WHEN p.publication_date >= current_date - 3 THEN 1.00
              WHEN p.publication_date >= current_date - 7 THEN 0.95
              ELSE 0.90
            END) AS rank_score
    FROM papers p
    WHERE p.is_ai_med = true
      AND p.quality_tier IN ('top', 'core')
      AND p.publication_date >= v_period_from  -- 严格时间窗口
      AND p.publication_date <= v_period_to
      -- 关键词匹配（如果用户设了关键词）
      AND (
        v_keywords IS NULL OR array_length(v_keywords, 1) IS NULL
        OR (
          EXISTS (
            SELECT 1 FROM unnest(v_expanded_synonyms) uk
            WHERE p.title ILIKE '%' || uk || '%' OR p.abstract ILIKE '%' || uk || '%'
               OR p.title_zh ILIKE '%' || uk || '%' OR p.abstract_zh ILIKE '%' || uk || '%'
          )
          AND EXISTS (
            SELECT 1 FROM unnest(v_title_required) tr
            WHERE p.title ILIKE '%' || tr || '%' OR p.title_zh ILIKE '%' || tr || '%'
               OR p.abstract ILIKE '%' || tr || '%' OR p.abstract_zh ILIKE '%' || tr || '%'
          )
        )
      )
      -- 期刊匹配（如果用户设了期刊）
      AND (
        v_journals IS NULL OR array_length(v_journals, 1) IS NULL
        OR EXISTS (SELECT 1 FROM unnest(v_journals) uj WHERE p.journal ILIKE '%' || uj || '%')
      )
    ORDER BY rank_score DESC, p.publication_date DESC
    LIMIT 5  -- 最多 5 篇，不够就不够
  )
  SELECT jsonb_agg(row_to_json(s.*) ORDER BY s.rank_score DESC), array_agg(s.id)
  INTO v_specialty_papers, v_specialty_ids
  FROM specialty s;

  -- ========================================
  -- 全局热点：本周质量最高的 1 篇（不限关键词）
  -- 严格 7 天窗口，排除已选的专科论文
  -- ========================================
  SELECT row_to_json(h.*)::jsonb INTO v_hotspot_paper
  FROM (
    SELECT p.id, p.title, p.title_zh, p.abstract_zh, p.journal, p.journal_if,
           p.journal_jcr, p.journal_cas_zone, p.publication_date, p.pubmed_url,
           p.quality_score, p.recommendation_reason
    FROM papers p
    WHERE p.is_ai_med = true
      AND p.quality_tier IN ('top', 'core')
      AND p.publication_date >= v_period_from
      AND p.publication_date <= v_period_to
      AND (v_specialty_ids IS NULL OR p.id <> ALL(v_specialty_ids))
    ORDER BY p.quality_score DESC, p.publication_date DESC
    LIMIT 1
  ) h;

  -- ========================================
  -- 跨界启发：本周与用户关键词不相关但高质量的 1 篇
  -- 严格 7 天窗口
  -- ========================================
  SELECT row_to_json(c.*)::jsonb INTO v_crossover_paper
  FROM (
    SELECT p.id, p.title, p.title_zh, p.abstract_zh, p.journal, p.journal_if,
           p.journal_jcr, p.journal_cas_zone, p.publication_date, p.pubmed_url,
           p.quality_score, p.recommendation_reason
    FROM papers p
    WHERE p.is_ai_med = true
      AND p.quality_tier IN ('top', 'core')
      AND p.publication_date >= v_period_from
      AND p.publication_date <= v_period_to
      AND (v_specialty_ids IS NULL OR p.id <> ALL(v_specialty_ids))
      AND (v_hotspot_paper IS NULL OR p.id <> (v_hotspot_paper->>'id')::uuid)
      -- 刻意排除用户关键词命中的（实现"跨界"效果）
      AND (
        v_keywords IS NULL OR array_length(v_keywords, 1) IS NULL
        OR NOT EXISTS (
          SELECT 1 FROM unnest(v_title_required) tr
          WHERE p.title ILIKE '%' || tr || '%' OR p.title_zh ILIKE '%' || tr || '%'
        )
      )
    ORDER BY p.quality_score DESC, random()
    LIMIT 1
  ) c;

  RETURN jsonb_build_object(
    'period_from', v_period_from,
    'period_to', v_period_to,
    'user_keywords', v_keywords,
    'specialty_papers', COALESCE(v_specialty_papers, '[]'::jsonb),
    'specialty_count', COALESCE(array_length(v_specialty_ids, 1), 0),
    'hotspot_paper', v_hotspot_paper,
    'crossover_paper', v_crossover_paper,
    -- 状态信息：方便前端/邮件判断是否"本周无相关文献"
    'has_specialty', COALESCE(array_length(v_specialty_ids, 1), 0) > 0,
    'has_hotspot', v_hotspot_paper IS NOT NULL,
    'has_crossover', v_crossover_paper IS NOT NULL
  );
END;
$function$

CREATE OR REPLACE FUNCTION public.get_journal_tier_and_weight(p_journal text)
 RETURNS TABLE(tier text, weight numeric, impact_factor numeric, jcr text, cas_zone text)
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_if numeric;
  v_jcr text;
  v_cas text;
  v_tier text;
  v_weight numeric;
BEGIN
  -- 1. 优先从白名单匹配
  SELECT jq.impact_factor, jq.jcr_quartile, jq.cas_zone, jq.tier, jq.weight
  INTO v_if, v_jcr, v_cas, v_tier, v_weight
  FROM journal_quality jq
  WHERE jq.is_active = true
    AND (lower(jq.journal_name) = lower(p_journal)
         OR EXISTS (SELECT 1 FROM unnest(jq.aliases) a WHERE lower(a) = lower(p_journal)))
  LIMIT 1;

  IF v_if IS NOT NULL THEN
    RETURN QUERY SELECT v_tier, v_weight, v_if, v_jcr, v_cas;
    RETURN;
  END IF;

  -- 2. 从 journal_if_cache 匹配（精确 + 模糊）
  SELECT jc.impact_factor, jc.jcr_quartile, jc.cas_zone
  INTO v_if, v_jcr, v_cas
  FROM journal_if_cache jc
  WHERE lower(jc.journal_name) = lower(p_journal)
     OR lower(jc.journal_abbr) = lower(p_journal)
     -- 模糊匹配：去掉标点和多余描述后匹配
     OR lower(p_journal) ILIKE '%' || lower(jc.journal_abbr) || '%'
     OR lower(jc.journal_name) ILIKE '%' || lower(p_journal) || '%'
     OR lower(p_journal) ILIKE '%' || lower(jc.journal_name) || '%'
  ORDER BY jc.impact_factor DESC  -- 优先匹配高分的
  LIMIT 1;

  IF v_if IS NOT NULL THEN
    v_tier := CASE WHEN v_if >= 10 THEN 'top' WHEN v_if >= 3 THEN 'core' ELSE 'emerging' END;
    v_weight := CASE 
      WHEN v_if >= 30 THEN 1.0 WHEN v_if >= 15 THEN 0.95 WHEN v_if >= 10 THEN 0.9
      WHEN v_if >= 5 THEN 0.8 WHEN v_if >= 3 THEN 0.7 ELSE 0.5
    END;
    RETURN QUERY SELECT v_tier, v_weight, v_if, v_jcr, v_cas;
    RETURN;
  END IF;

  -- 3. 完全未知
  RETURN QUERY SELECT 'emerging'::text, 0.5::numeric, NULL::numeric, NULL::text, NULL::text;
END;
$function$

CREATE OR REPLACE FUNCTION public.get_or_flag_keyword(p_keyword text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_synonyms text[];
  v_template text;
  v_title_required text[];
BEGIN
  SELECT synonyms, title_required, pubmed_query_template 
  INTO v_synonyms, v_title_required, v_template
  FROM keyword_synonyms
  WHERE lower(canonical_keyword) = lower(p_keyword)
  LIMIT 1;

  IF v_synonyms IS NOT NULL THEN
    RETURN jsonb_build_object(
      'status', 'cached',
      'keyword', p_keyword,
      'has_pubmed_query', v_template IS NOT NULL AND v_template != ''
    );
  ELSE
    RETURN jsonb_build_object(
      'status', 'needs_llm',
      'keyword', p_keyword,
      'prompt', format(
'你是一名医学信息检索专家，精通PubMed数据库的检索策略。请为以下医学术语生成专业的PubMed检索式。

输入术语：%s

要求：
1. 生成该术语的医学方向检索式（不含AI部分，AI部分由系统自动拼接）
2. 必须使用MeSH主题词（[Mesh]）+ 自由词（[Title/Abstract]）双重策略
3. 包含该术语的所有常见英文表达、缩写、近义词
4. 使用通配符（*）匹配词形变化
5. 同时提供用于判断论文相关性的英文关键词列表

严格按以下JSON格式输出，不要加任何前缀文字或markdown：
{
  "pubmed_query": "医学方向的PubMed检索式，例如：(\"Cardiovascular Diseases\"[Mesh] OR cardiovascular[Title/Abstract] OR cardiac[Title/Abstract])",
  "synonyms": ["英文同义词1", "英文同义词2"],
  "title_required": ["标题必须包含的关键词1", "关键词2"]
}', p_keyword)
    );
  END IF;
END;
$function$

CREATE OR REPLACE FUNCTION public.get_papers_for_openclaw(p_limit integer DEFAULT 20)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
AS $function$
  SELECT jsonb_build_object(
    'total', (SELECT count(*) FROM papers 
              WHERE is_ai_med = true 
              AND (title_zh IS NULL OR abstract_zh IS NULL OR recommendation_reason IS NULL)),
    'papers', COALESCE(jsonb_agg(row_to_json(sub.*)), '[]'::jsonb)
  )
  FROM (
    SELECT id, pmid, title, abstract, journal, journal_if, journal_jcr, 
           journal_cas_zone, publication_date, quality_score, quality_tier,
           title_zh IS NOT NULL AS has_title_zh,
           abstract_zh IS NOT NULL AS has_abstract_zh,
           recommendation_reason IS NOT NULL AS has_recommendation
    FROM papers
    WHERE is_ai_med = true
      AND (title_zh IS NULL OR abstract_zh IS NULL OR recommendation_reason IS NULL)
    ORDER BY quality_score DESC, publication_date DESC
    LIMIT p_limit
  ) sub
$function$

CREATE OR REPLACE FUNCTION public.get_personalized_feed(p_user_id uuid, p_page integer DEFAULT 1, p_page_size integer DEFAULT 20)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_user_keywords text[];
  v_custom_journals text[];
  v_expanded_synonyms text[] := '{}';
  v_title_required text[] := '{}';
  v_result jsonb;
  v_total int;
  v_offset int;
  v_kw text;
  v_cutoff_date date := current_date - 30;  -- 硬性截止：30天
BEGIN
  v_offset := (p_page - 1) * p_page_size;

  SELECT subscription_keywords, custom_journals
  INTO v_user_keywords, v_custom_journals
  FROM profiles WHERE id = p_user_id;

  -- 同义词扩展
  IF v_user_keywords IS NOT NULL AND array_length(v_user_keywords, 1) > 0 THEN
    FOREACH v_kw IN ARRAY v_user_keywords LOOP
      DECLARE v_syn text[]; v_req text[];
      BEGIN
        SELECT synonyms, title_required INTO v_syn, v_req
        FROM keyword_synonyms WHERE lower(canonical_keyword) = lower(v_kw) LIMIT 1;
        IF v_syn IS NOT NULL THEN
          v_expanded_synonyms := v_expanded_synonyms || v_syn;
          v_title_required := v_title_required || v_req;
        ELSE
          v_expanded_synonyms := v_expanded_synonyms || ARRAY[v_kw];
          v_title_required := v_title_required || ARRAY[v_kw];
        END IF;
      END;
    END LOOP;
  END IF;

  -- 计算总数
  SELECT count(*) INTO v_total
  FROM papers p
  WHERE p.is_ai_med = true
    AND p.quality_tier IN ('top', 'core')
    AND p.publication_date >= v_cutoff_date  -- 硬性时间截止
    AND (v_custom_journals IS NULL OR array_length(v_custom_journals, 1) IS NULL
         OR EXISTS (SELECT 1 FROM unnest(v_custom_journals) uj WHERE p.journal ILIKE '%' || uj || '%'))
    AND (array_length(v_user_keywords, 1) IS NULL OR v_user_keywords IS NULL
         OR (EXISTS (SELECT 1 FROM unnest(v_expanded_synonyms) uk
                     WHERE p.title ILIKE '%' || uk || '%' OR p.abstract ILIKE '%' || uk || '%'
                        OR p.title_zh ILIKE '%' || uk || '%' OR p.abstract_zh ILIKE '%' || uk || '%')
             AND EXISTS (SELECT 1 FROM unnest(v_title_required) tr
                         WHERE p.title ILIKE '%' || tr || '%' OR p.title_zh ILIKE '%' || tr || '%'
                            OR p.abstract ILIKE '%' || tr || '%' OR p.abstract_zh ILIKE '%' || tr || '%')));

  -- 获取分页结果
  SELECT jsonb_build_object(
    'total', v_total, 'page', p_page, 'page_size', p_page_size,
    'papers', COALESCE(jsonb_agg(row_to_json(sub.*)), '[]'::jsonb)
  ) INTO v_result
  FROM (
    SELECT p.id, p.title, p.title_zh, p.abstract, p.abstract_zh, p.journal,
           p.publication_date, p.ai_med_score, p.quality_score, p.quality_tier,
           p.pubmed_url, p.is_open_access, p.oa_pdf_url, p.keywords, p.mesh_terms,
           p.journal_if, p.journal_jcr, p.journal_cas_zone,
           p.recommendation_reason,
           -- 排序：质量分 × 时效性衰减（7天内满分，之后快速衰减）
           (p.quality_score * CASE
              WHEN p.publication_date >= current_date - 7 THEN 1.00
              WHEN p.publication_date >= current_date - 14 THEN 0.85
              WHEN p.publication_date >= current_date - 21 THEN 0.70
              WHEN p.publication_date >= current_date - 30 THEN 0.55
              ELSE 0.30  -- 不会到这里，因为有 cutoff
            END) AS final_score
    FROM papers p
    WHERE p.is_ai_med = true
      AND p.quality_tier IN ('top', 'core')
      AND p.publication_date >= v_cutoff_date  -- 硬性时间截止
      AND (v_custom_journals IS NULL OR array_length(v_custom_journals, 1) IS NULL
           OR EXISTS (SELECT 1 FROM unnest(v_custom_journals) uj WHERE p.journal ILIKE '%' || uj || '%'))
      AND (array_length(v_user_keywords, 1) IS NULL OR v_user_keywords IS NULL
           OR (EXISTS (SELECT 1 FROM unnest(v_expanded_synonyms) uk
                       WHERE p.title ILIKE '%' || uk || '%' OR p.abstract ILIKE '%' || uk || '%'
                          OR p.title_zh ILIKE '%' || uk || '%' OR p.abstract_zh ILIKE '%' || uk || '%')
               AND EXISTS (SELECT 1 FROM unnest(v_title_required) tr
                           WHERE p.title ILIKE '%' || tr || '%' OR p.title_zh ILIKE '%' || tr || '%'
                              OR p.abstract ILIKE '%' || tr || '%' OR p.abstract_zh ILIKE '%' || tr || '%')))
    ORDER BY final_score DESC, p.publication_date DESC
    LIMIT p_page_size OFFSET v_offset
  ) sub;

  RETURN v_result;
END;
$function$

CREATE OR REPLACE FUNCTION public.handle_new_user_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, contact_email)
  values (new.id, new.email)
  on conflict (id) do update
    set contact_email = excluded.contact_email,
        updated_at = now();
  return new;
end;
$function$

CREATE OR REPLACE FUNCTION public.is_admin(uid uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role = 'admin'
  );
$function$

CREATE OR REPLACE FUNCTION public.openclaw_update_paper(p_paper_id uuid, p_title_zh text DEFAULT NULL::text, p_abstract_zh text DEFAULT NULL::text, p_recommendation_reason text DEFAULT NULL::text, p_recommendation_reason_en text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE papers SET
    title_zh = COALESCE(p_title_zh, title_zh),
    abstract_zh = COALESCE(p_abstract_zh, abstract_zh),
    recommendation_reason = COALESCE(p_recommendation_reason, recommendation_reason),
    recommendation_reason_en = COALESCE(p_recommendation_reason_en, recommendation_reason_en),
    llm_processed_at = now(),
    updated_at = now()
  WHERE id = p_paper_id;
  
  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'error', 'reason', 'paper_not_found');
  END IF;
  
  RETURN jsonb_build_object('status', 'success', 'paper_id', p_paper_id);
END;
$function$

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$

CREATE OR REPLACE FUNCTION public.save_llm_synonyms(p_keyword text, p_synonyms text[], p_title_required text[])
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
BEGIN
  INSERT INTO keyword_synonyms (canonical_keyword, synonyms, title_required, source, llm_generated_at)
  VALUES (p_keyword, 
          -- 把中文原词也加进去
          array_cat(ARRAY[p_keyword], p_synonyms), 
          array_cat(ARRAY[p_keyword], p_title_required),
          'llm', now())
  ON CONFLICT (canonical_keyword) DO UPDATE SET
    synonyms = array_cat(keyword_synonyms.synonyms, EXCLUDED.synonyms),
    title_required = array_cat(keyword_synonyms.title_required, EXCLUDED.title_required),
    source = 'merged',
    llm_generated_at = now(),
    updated_at = now();

  RETURN jsonb_build_object('status', 'saved', 'keyword', p_keyword);
END;
$function$

CREATE OR REPLACE FUNCTION public.save_llm_synonyms(p_keyword text, p_synonyms text[], p_title_required text[], p_pubmed_query text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
BEGIN
  INSERT INTO keyword_synonyms (
    canonical_keyword, synonyms, title_required, pubmed_query_template, source, llm_generated_at
  )
  VALUES (
    p_keyword, 
    array_cat(ARRAY[p_keyword], p_synonyms), 
    array_cat(ARRAY[p_keyword], p_title_required),
    p_pubmed_query,
    'llm', now()
  )
  ON CONFLICT (canonical_keyword) DO UPDATE SET
    synonyms = array_cat(keyword_synonyms.synonyms, EXCLUDED.synonyms),
    title_required = array_cat(keyword_synonyms.title_required, EXCLUDED.title_required),
    pubmed_query_template = COALESCE(EXCLUDED.pubmed_query_template, keyword_synonyms.pubmed_query_template),
    source = 'merged',
    llm_generated_at = now(),
    updated_at = now();

  RETURN jsonb_build_object('status', 'saved', 'keyword', p_keyword);
END;
$function$

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$

CREATE OR REPLACE FUNCTION public.sync_profile_email_from_auth()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  update public.profiles
     set contact_email = new.email,
         updated_at = now()
   where id = new.id;
  return new;
end;
$function$

CREATE OR REPLACE FUNCTION public.url_encode_pubmed(s text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
  SELECT replace(replace(replace(replace(replace(replace(s, 
    ' ', '+'),
    '"', '%22'),
    '[', '%5B'),
    ']', '%5D'),
    '/', '%2F'),
    ':', '%3A')
$function$

-- Non-constraint indexes
CREATE INDEX idx_ai_queue_paper ON public.ai_analysis_queue USING btree (paper_id);
CREATE INDEX idx_ai_queue_status_priority ON public.ai_analysis_queue USING btree (status, priority DESC, created_at);
CREATE INDEX idx_ai_queue_user ON public.ai_analysis_queue USING btree (user_id);
CREATE INDEX idx_ai_digest_log_user ON public.ai_digest_log USING btree (user_id, created_at DESC);
CREATE INDEX idx_byok_usage_type ON public.byok_usage_log USING btree (usage_type);
CREATE INDEX idx_byok_usage_user ON public.byok_usage_log USING btree (user_id, created_at DESC);
CREATE INDEX idx_feed_rec_source ON public.feed_recommendations USING btree (source_type);
CREATE INDEX idx_feed_rec_user_batch ON public.feed_recommendations USING btree (user_id, batch_date DESC, recommendation_score DESC);
CREATE INDEX idx_jif_eissn ON public.journal_if_cache USING btree (eissn) WHERE ((eissn IS NOT NULL) AND (eissn <> '.'::text));
CREATE INDEX idx_jif_issn ON public.journal_if_cache USING btree (issn) WHERE ((issn IS NOT NULL) AND (issn <> '.'::text));
CREATE INDEX idx_jif_name ON public.journal_if_cache USING btree (lower(journal_name));
CREATE INDEX idx_journal_quality_active ON public.journal_quality USING btree (is_active);
CREATE INDEX idx_journal_quality_aliases_gin ON public.journal_quality USING gin (aliases);
CREATE INDEX idx_journal_quality_es_last_sync ON public.journal_quality USING btree (es_last_sync_at DESC NULLS LAST);
CREATE INDEX idx_journal_quality_es_status ON public.journal_quality USING btree (es_sync_status);
CREATE INDEX idx_journal_quality_if_desc ON public.journal_quality USING btree (impact_factor DESC NULLS LAST);
CREATE INDEX idx_journal_quality_name_lower ON public.journal_quality USING btree (lower(journal_name));
CREATE INDEX idx_journal_quality_tier ON public.journal_quality USING btree (tier);
CREATE INDEX idx_journal_sync_log_jq ON public.journal_sync_log USING btree (journal_quality_id, started_at DESC);
CREATE INDEX idx_keyword_synonyms_canonical ON public.keyword_synonyms USING btree (lower(canonical_keyword));
CREATE INDEX idx_prt_paper ON public.paper_research_topics USING btree (paper_id);
CREATE INDEX idx_prt_topic ON public.paper_research_topics USING btree (topic_id);
CREATE INDEX idx_paper_topics_topic ON public.paper_topics USING btree (topic);
CREATE INDEX idx_papers_ai_med_score_desc ON public.papers USING btree (ai_med_score DESC);
CREATE INDEX idx_papers_fetched_at_desc ON public.papers USING btree (fetched_at DESC);
CREATE INDEX idx_papers_is_ai_med ON public.papers USING btree (is_ai_med);
CREATE INDEX idx_papers_is_ai_med_quality ON public.papers USING btree (is_ai_med, quality_tier, quality_score DESC);
CREATE INDEX idx_papers_is_open_access ON public.papers USING btree (is_open_access);
CREATE INDEX idx_papers_keywords_gin ON public.papers USING gin (keywords);
CREATE INDEX idx_papers_mesh_terms_gin ON public.papers USING gin (mesh_terms);
CREATE INDEX idx_papers_oa_pdf_url_nonnull ON public.papers USING btree (oa_pdf_url) WHERE (oa_pdf_url IS NOT NULL);
CREATE INDEX idx_papers_publication_date_desc ON public.papers USING btree (publication_date DESC NULLS LAST);
CREATE INDEX idx_papers_quality_score_desc ON public.papers USING btree (quality_score DESC);
CREATE INDEX idx_profiles_is_active ON public.profiles USING btree (is_active);
CREATE INDEX idx_profiles_keywords_gin ON public.profiles USING gin (subscription_keywords);
CREATE INDEX idx_profiles_mesh_gin ON public.profiles USING gin (subscription_mesh_terms);
CREATE INDEX idx_push_issue_items_rank ON public.push_issue_items USING btree (issue_id, rank);
CREATE INDEX idx_push_issues_week ON public.push_issues USING btree (issue_week_start DESC);
CREATE INDEX idx_subject_search_terms_gin ON public.subject_categories USING gin (search_terms);
CREATE INDEX idx_ujs_journal ON public.user_journal_subscriptions USING btree (journal_quality_id);
CREATE INDEX idx_ujs_user ON public.user_journal_subscriptions USING btree (user_id);
CREATE INDEX idx_user_paper_interactions_paper ON public.user_paper_interactions USING btree (paper_id);
CREATE INDEX idx_user_paper_interactions_user_fav ON public.user_paper_interactions USING btree (user_id, is_favorited);
CREATE INDEX idx_user_paper_interactions_user_updated ON public.user_paper_interactions USING btree (user_id, updated_at DESC);
CREATE INDEX idx_uts_user ON public.user_topic_subscriptions USING btree (user_id);
CREATE INDEX user_weekly_push_deliveries_issue_idx ON public.user_weekly_push_deliveries USING btree (issue_id);
CREATE INDEX user_weekly_push_deliveries_user_idx ON public.user_weekly_push_deliveries USING btree (user_id, issue_week_start DESC);
CREATE INDEX idx_uwsd_issue_week_status ON public.user_weekly_spotlight_deliveries USING btree (issue_week_start DESC, status);
CREATE INDEX idx_uwsd_user_sent_at ON public.user_weekly_spotlight_deliveries USING btree (user_id, sent_at DESC);
CREATE INDEX idx_weekly_reports_status ON public.weekly_reports USING btree (email_status) WHERE (email_status = 'pending'::text);
CREATE INDEX idx_weekly_reports_user ON public.weekly_reports USING btree (user_id, period_to DESC);

-- Row level security
alter table "public"."ai_analysis_queue" enable row level security;
alter table "public"."ai_digest_log" enable row level security;
alter table "public"."byok_usage_log" enable row level security;
alter table "public"."feed_recommendations" enable row level security;
alter table "public"."journal_if_cache" enable row level security;
alter table "public"."journal_quality" enable row level security;
alter table "public"."journal_sync_log" enable row level security;
alter table "public"."keyword_synonyms" enable row level security;
alter table "public"."paper_research_topics" enable row level security;
alter table "public"."paper_topics" enable row level security;
alter table "public"."papers" enable row level security;
alter table "public"."profiles" enable row level security;
alter table "public"."push_issue_items" enable row level security;
alter table "public"."push_issues" enable row level security;
alter table "public"."research_topics" enable row level security;
alter table "public"."subject_categories" enable row level security;
alter table "public"."sync_state" enable row level security;
alter table "public"."user_journal_subscriptions" enable row level security;
alter table "public"."user_paper_interactions" enable row level security;
alter table "public"."user_topic_subscriptions" enable row level security;
alter table "public"."user_weekly_push_deliveries" enable row level security;
alter table "public"."user_weekly_spotlight_deliveries" enable row level security;
alter table "public"."weekly_reports" enable row level security;

-- RLS policies
drop policy if exists "ai_queue_insert_own" on "public"."ai_analysis_queue";
create policy "ai_queue_insert_own"
on "public"."ai_analysis_queue"
as permissive
for insert
with check ((user_id = auth.uid()));

drop policy if exists "ai_queue_select_own" on "public"."ai_analysis_queue";
create policy "ai_queue_select_own"
on "public"."ai_analysis_queue"
as permissive
for select
using (((user_id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "ai_digest_log_select_own" on "public"."ai_digest_log";
create policy "ai_digest_log_select_own"
on "public"."ai_digest_log"
as permissive
for select
using (((user_id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "byok_usage_select_own" on "public"."byok_usage_log";
create policy "byok_usage_select_own"
on "public"."byok_usage_log"
as permissive
for select
using (((user_id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "feed_rec_select_own" on "public"."feed_recommendations";
create policy "feed_rec_select_own"
on "public"."feed_recommendations"
as permissive
for select
using (((user_id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "journal_quality_select_authenticated" on "public"."journal_quality";
create policy "journal_quality_select_authenticated"
on "public"."journal_quality"
as permissive
for select
using (true);

drop policy if exists "paper_research_topics_select_authenticated" on "public"."paper_research_topics";
create policy "paper_research_topics_select_authenticated"
on "public"."paper_research_topics"
as permissive
for select
using (true);

drop policy if exists "paper_topics_select_authenticated" on "public"."paper_topics";
create policy "paper_topics_select_authenticated"
on "public"."paper_topics"
as permissive
for select
using (true);

drop policy if exists "papers_select_authenticated" on "public"."papers";
create policy "papers_select_authenticated"
on "public"."papers"
as permissive
for select
using (true);

drop policy if exists "profiles_delete_admin" on "public"."profiles";
create policy "profiles_delete_admin"
on "public"."profiles"
as permissive
for delete
using (is_admin(auth.uid()));

drop policy if exists "profiles_insert_self" on "public"."profiles";
create policy "profiles_insert_self"
on "public"."profiles"
as permissive
for insert
with check (((id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "profiles_select_own_or_admin" on "public"."profiles";
create policy "profiles_select_own_or_admin"
on "public"."profiles"
as permissive
for select
using (((id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "profiles_update_own_or_admin" on "public"."profiles";
create policy "profiles_update_own_or_admin"
on "public"."profiles"
as permissive
for update
using (((id = auth.uid()) OR is_admin(auth.uid())))
with check (((id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "push_issue_items_select_authenticated" on "public"."push_issue_items";
create policy "push_issue_items_select_authenticated"
on "public"."push_issue_items"
as permissive
for select
using (true);

drop policy if exists "push_issues_select_authenticated" on "public"."push_issues";
create policy "push_issues_select_authenticated"
on "public"."push_issues"
as permissive
for select
using (true);

drop policy if exists "research_topics_select_authenticated" on "public"."research_topics";
create policy "research_topics_select_authenticated"
on "public"."research_topics"
as permissive
for select
using (true);

drop policy if exists "subject_select_authenticated" on "public"."subject_categories";
create policy "subject_select_authenticated"
on "public"."subject_categories"
as permissive
for select
using (true);

drop policy if exists "sync_state_no_client_access" on "public"."sync_state";
create policy "sync_state_no_client_access"
on "public"."sync_state"
as permissive
for all
using (false)
with check (false);

drop policy if exists "ujs_admin_all" on "public"."user_journal_subscriptions";
create policy "ujs_admin_all"
on "public"."user_journal_subscriptions"
as permissive
for all
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "ujs_delete_own" on "public"."user_journal_subscriptions";
create policy "ujs_delete_own"
on "public"."user_journal_subscriptions"
as permissive
for delete
using ((user_id = auth.uid()));

drop policy if exists "ujs_insert_own" on "public"."user_journal_subscriptions";
create policy "ujs_insert_own"
on "public"."user_journal_subscriptions"
as permissive
for insert
with check ((user_id = auth.uid()));

drop policy if exists "ujs_select_own" on "public"."user_journal_subscriptions";
create policy "ujs_select_own"
on "public"."user_journal_subscriptions"
as permissive
for select
using (((user_id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "upi_delete_own_or_admin" on "public"."user_paper_interactions";
create policy "upi_delete_own_or_admin"
on "public"."user_paper_interactions"
as permissive
for delete
using (((user_id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "upi_insert_own" on "public"."user_paper_interactions";
create policy "upi_insert_own"
on "public"."user_paper_interactions"
as permissive
for insert
with check ((user_id = auth.uid()));

drop policy if exists "upi_select_own_or_admin" on "public"."user_paper_interactions";
create policy "upi_select_own_or_admin"
on "public"."user_paper_interactions"
as permissive
for select
using (((user_id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "upi_update_own_or_admin" on "public"."user_paper_interactions";
create policy "upi_update_own_or_admin"
on "public"."user_paper_interactions"
as permissive
for update
using (((user_id = auth.uid()) OR is_admin(auth.uid())))
with check (((user_id = auth.uid()) OR is_admin(auth.uid())));

drop policy if exists "uts_admin_all" on "public"."user_topic_subscriptions";
create policy "uts_admin_all"
on "public"."user_topic_subscriptions"
as permissive
for all
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "uts_delete_own" on "public"."user_topic_subscriptions";
create policy "uts_delete_own"
on "public"."user_topic_subscriptions"
as permissive
for delete
using ((user_id = auth.uid()));

drop policy if exists "uts_insert_own" on "public"."user_topic_subscriptions";
create policy "uts_insert_own"
on "public"."user_topic_subscriptions"
as permissive
for insert
with check ((user_id = auth.uid()));

drop policy if exists "uts_select_own" on "public"."user_topic_subscriptions";
create policy "uts_select_own"
on "public"."user_topic_subscriptions"
as permissive
for select
using ((user_id = auth.uid()));

drop policy if exists "uts_update_own" on "public"."user_topic_subscriptions";
create policy "uts_update_own"
on "public"."user_topic_subscriptions"
as permissive
for update
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));

drop policy if exists "user_weekly_push_deliveries_select_own" on "public"."user_weekly_push_deliveries";
create policy "user_weekly_push_deliveries_select_own"
on "public"."user_weekly_push_deliveries"
as permissive
for select
using ((auth.uid() = user_id));

drop policy if exists "uwsd_select_own_or_admin" on "public"."user_weekly_spotlight_deliveries";
create policy "uwsd_select_own_or_admin"
on "public"."user_weekly_spotlight_deliveries"
as permissive
for select
using (((user_id = auth.uid()) OR is_admin(auth.uid())));

-- Triggers
drop trigger if exists "trg_ai_queue_set_updated_at" on "public"."ai_analysis_queue";
CREATE TRIGGER trg_ai_queue_set_updated_at BEFORE UPDATE ON ai_analysis_queue FOR EACH ROW EXECUTE FUNCTION set_updated_at();

drop trigger if exists "trg_papers_set_updated_at" on "public"."papers";
CREATE TRIGGER trg_papers_set_updated_at BEFORE UPDATE ON papers FOR EACH ROW EXECUTE FUNCTION set_updated_at();

drop trigger if exists "trg_profiles_set_updated_at" on "public"."profiles";
CREATE TRIGGER trg_profiles_set_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

drop trigger if exists "trg_subject_set_updated_at" on "public"."subject_categories";
CREATE TRIGGER trg_subject_set_updated_at BEFORE UPDATE ON subject_categories FOR EACH ROW EXECUTE FUNCTION set_updated_at();

drop trigger if exists "trg_ujs_set_updated_at" on "public"."user_journal_subscriptions";
CREATE TRIGGER trg_ujs_set_updated_at BEFORE UPDATE ON user_journal_subscriptions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

drop trigger if exists "trg_user_paper_interactions_set_updated_at" on "public"."user_paper_interactions";
CREATE TRIGGER trg_user_paper_interactions_set_updated_at BEFORE UPDATE ON user_paper_interactions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
